version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: gshark-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: gshark-server
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.21
    container_name: gshark-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /data/application/init.sql
    volumes: 
      - ./init.sql:/data/application/init.sql
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'gshark' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'gshark' # root管理员用户密码
      MYSQL_ROOT_USER: root
    networks:
      network:
        ipv4_address: 177.7.0.13

  scanner:
    build:
      context: ./server
      dockerfile: ./ScannerDockerfile
    container_name: gshark-scanner
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      network:
        ipv4_address: 177.7.0.14
    environment:
      GSHARK_CONFIG: /gshark/server/config.docker.yaml