captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
email:
  to: xxx@qq.com
  port: 465
  from: xxx@qq.com
  host: smtp.qq.com
  is-ssl: true
  secret: xxx
  nickname: test
  enable: false
excel:
  dir: ./resource/excel/
jwt:
  signing-key: qmPlus
  expires-time: 604800
  buffer-time: 86400
local:
  path: uploads/file
mysql:
  path: localhost:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gshark
  username: root
  password: madneal
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap:
search:
  gobuster-filepath:
  subdomain-wordlist:
  searchnum: 10
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  gitlab-base:
  ai_server:
  ai_token:
wechat:
  url:
  enable: false
zap:
  level: info
  format: console
  prefix: '[GShark]'
  director: log
  link-name: latest_log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
